[tool.poetry]
name = "course-project"
version = "0.1.0"
description = ""
authors = ["shwwdnl <shwwdnl@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "7.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
